### ISSUE TITLE
adapt Housing_needs_units_targets - Alt.sas and Housing_needs_units_targets.sas

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/NCHsg#6]
- [x] Adapt these programs from the Regional Housing Framework for North Carolina. I'll give you notes.

- [x] add in the creation of a structure type categorical variable. (SF, 2-9, 10+ and mobile/other) 

- [x] add in code from natural affordable rental stock to create structureyear category and unitcount and affordable flags. (adjust affordable $ to match NC categories). 

- [x] These programs didn't save a data set after the new variable creation and merging years but you should. Move the output to a separate program.

**Comment by maggiesu0725** [comment]
@lhendey do you remember in the RegHsg natural affordable rental stock calculation, how was the threshold (1300) determined?

**Comment by lhendey** [comment]
@maggiesu0725 it was based on our breaks in the study for housing costs. it roughly matched 5o% of AMI

**Comment by maggiesu0725** [comment]
NCHousing_needs_units_targets.log
NCHousing_needs_units_targets - Alt.log
